### ISSUE TITLE
it won't run on anki 2.1.51

### ISSUE THREAD

**Issue by aliafshany** [glutanimate/review-heatmap#148]
#### Problem description

i was using anki 2.1.49, and ten i decided to upgrade my Anki which ened on this add-on failure.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.51 (cf78a555) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 11.6.2
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-05-02 19:32:59
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 217, in <lambda>
    options_action.triggered.connect(lambda _: invokeOptionsDialog())
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 209, in invokeOptionsDialog
    dialog = RevHmOptions(config, mw, parent=parent)
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/gui/options.py", line 107, in __init__
    super(RevHmOptions, self).__init__(
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/dialog_options.py", line 81, in __init__
    super(OptionsDialog, self).__init__(
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 154, in __init__
    self.setData(data)
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/dialog_mapped.py", line 162, in setData
    self.interface.set(widget_name, key, value)
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 270, in set
    return setter(widget, data)
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 354, in setValue
    self._setDateTime(widget, data)
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 800, in _setDateTime
    return qdatetimeedit.setDateTime(self._createDateTimeFromUnix(curtime))
  File "/Users/afshany/Library/Application Support/Anki2/addons21/review_heatmap/libaddon/gui/basic/interface.py", line 793, in _createDateTimeFromUnix
    qdatetime.setTime_t(unixtime)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by aliafshany** [comment]
this is what it looks like now

![image](https://user-images.githubusercontent.com/40741745/166259257-1f44aa1d-6cc7-4614-9f20-3147e5ce8963.png)

**Comment by aliafshany** [comment]
it is because of QT6 which review-heatmap is not compatibale with this  yet.

**Comment by rbereziuk** [comment]
The author of the plugin wrote about the update

> Update (2022-04-09): Currently putting the final touches on the next Review Heatmap update which will add support for Anki 2.1.50. The release will be next week, so please stay tuned!

https://ankiweb.net/shared/info/1771074083

**Comment by aliafshany** [comment]
the pluggin works on 2.1.51
the problem was QT6, if you install qt5 version everythong would work great

**Comment by ChrisNiekler** [comment]
I think the[ qt5 does not work ](https://docs.ankiweb.net/platform/linux/installing.html#:~:text=Compatibility%20with%20recent%20glibc%20versions%20(fixes%20blank%20screens%20on%20recent%20distros).)with the Ubuntu LTS 22.04 and PopOS! LTS 22.04. So users of Linux-based operating systems can not use it right now. There is a bug where the deck screen is just blank.

**Comment by angelaambroz** [comment]
The blank deck screen can be fixed (only?) on QT6. But yeah, then you have no review heatmap. :sob:

**Comment by jacopofar** [comment]
As a workaround you can use `QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox" anki` to start the Qt5 version, it works for me on Fedora under Wayland. Qt6 does not need that, but breaks the plugin
